/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as AgentRunsRouteImport } from './routes/agent-runs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReposRepoIdRouteImport } from './routes/repos.$repoId'

const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRunsRoute = AgentRunsRouteImport.update({
  id: '/agent-runs',
  path: '/agent-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRepoIdRoute = ReposRepoIdRouteImport.update({
  id: '/repos/$repoId',
  path: '/repos/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-runs': typeof AgentRunsRoute
  '/integrations': typeof IntegrationsRoute
  '/repos/$repoId': typeof ReposRepoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-runs': typeof AgentRunsRoute
  '/integrations': typeof IntegrationsRoute
  '/repos/$repoId': typeof ReposRepoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-runs': typeof AgentRunsRoute
  '/integrations': typeof IntegrationsRoute
  '/repos/$repoId': typeof ReposRepoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agent-runs' | '/integrations' | '/repos/$repoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent-runs' | '/integrations' | '/repos/$repoId'
  id: '__root__' | '/' | '/agent-runs' | '/integrations' | '/repos/$repoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRunsRoute: typeof AgentRunsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  ReposRepoIdRoute: typeof ReposRepoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-runs': {
      id: '/agent-runs'
      path: '/agent-runs'
      fullPath: '/agent-runs'
      preLoaderRoute: typeof AgentRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$repoId': {
      id: '/repos/$repoId'
      path: '/repos/$repoId'
      fullPath: '/repos/$repoId'
      preLoaderRoute: typeof ReposRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRunsRoute: AgentRunsRoute,
  IntegrationsRoute: IntegrationsRoute,
  ReposRepoIdRoute: ReposRepoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
